version: "3.7"
services:
  mysql:
    container_name: mysql
    command: --default-authentication-plugin=mysql_native_password
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    volumes:
      - ./dockercompose/mysql:/var/lib/mysql
    networks:
      - sa-network
  mongo:
    container_name: mongo
    image: mongo:latest
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - "./dockercompose/mongo/:/data/db"
    ports:
      - "27017:27017"
    networks:
      - sa-network
  redis:
    container_name: redis
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - sa-network
networks:
  sa-network:
    name: sa-network
